name: telegram-download

on:
    workflow_dispatch:

jobs:
    download:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - run: npm install

            - name: Run downloader
              run: node download.js
              env:
                  TG_API_ID: ${{ secrets.TG_API_ID }}
                  TG_API_HASH: ${{ secrets.TG_API_HASH }}
                  TG_SESSION: ${{ secrets.TG_SESSION }}

            - name: Commit files
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com

                  git add downloads

                  git diff --cached --quiet || git commit -m "telegram files"

                  git push
